name: Build and Test (vcpkg)

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build and Test (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            triplet: arm64-osx-release
          - os: ubuntu-24.04
            triplet: x64-linux-release
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
      VCPKG_DEFAULT_HOST_TRIPLET: ${{ matrix.triplet }}
    steps:
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: true

      - name: Set up cmake and ninja
        uses: lukka/get-cmake@6b3e96a9bc9976b8b546346fdd102effedae0ca8 # v4.0.3

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@5e0cab206a5ea620130caf672fce3e4a6b5666a1 # v11.5

      - name: Build
        run: |
          cmake -B build --toolchain vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build build

      - name: Test
        run: ctest --test-dir build

      - name: Install
        run: sudo cmake --install build

      - name: Smoke test
        run: |
          cmake -B build --toolchain ../vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build build
          ./build/ci-cmake
          ./build/ci-pkgconfig
        working-directory: ci
