name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prepare:
    name: Prepare list of configurations
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      presets: ${{ steps.set-matrix.outputs.presets }}
    steps:
      - name: Check out the source code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set matrix
        id: set-matrix
        run: echo presets="$(jq '.configurePresets[] | select(.hidden == false) | {name, description}' CMakePresets.json | jq --slurp -c .)" >> "${GITHUB_OUTPUT}"

  build:
    needs: prepare
    name: Build and Test (${{ matrix.preset.description }})
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        preset: ${{ fromJson(needs.prepare.outputs.presets) }}
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: true

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build and test
        run: |
          cmake --preset ${{ matrix.preset.name }}
          cmake --build --preset ${{ matrix.preset.name }} -j $(nproc)
          ctest --preset ${{ matrix.preset.name }}

  smoke:
    name: Smoke test
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build and install
        run: |
          cmake -B build
          cmake --build build
          sudo cmake --install build

      - name: Smoke test
        run: |
          set -x
          cmake -B build
          cmake --build build
          ./build/ci-cmake
          ./build/ci-pkgconfig
        working-directory: ci
