name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build
        run: |
          cmake -B build
          cmake --build build

      - name: Test
        run: ctest --test-dir build
