name: Lint C++ code

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: none

jobs:
  lint:
    name: clang-format (${{ matrix.path }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path:
          - src
          - test
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: clang-format Check
        uses: jidicula/clang-format-action@c74383674bf5f7c69f60ce562019c1c94bc1421a # v4.13.0
        with:
          clang-format-version: 18
          check-path: ${{ matrix.path }}
